
#Install kernel, disable speaker and configure grub
---
- name: Disable pcspeaker.
  blockinfile:
    create: yes
    dest: "/etc/modprobe.d/nobeep"
    block: |
      blacklist pcspkr

- name: Install xz-utils package.
  apt:
    name: xz-utils

- name: Download kernel debs
  get_url:
    url: "{{ item }}"
    dest: "/root/"
  with_items:
    - "https://www.dropbox.com/s/bvpzpcqtji4aky4/linux-image-5.9.16_5.9.16-1_amd64.deb?dl=1"
    - "https://www.dropbox.com/s/gi6q03x6qfq2suj/linux-headers-5.9.16_5.9.16-1_amd64.deb?dl=1"
    - "https://www.dropbox.com/s/ghimievgzvliogw/linux-libc-dev_5.9.16-1_amd64.deb?dl=1"
    - "https://www.dropbox.com/s/kz6z53x3mbrk1i6/linux-image-5.9.16_5.9.16-1_i386.deb?dl=1"
    - "https://www.dropbox.com/s/2vigiq7h5bp8n37/linux-headers-5.9.16_5.9.16-1_i386.deb?dl=1"
    - "https://www.dropbox.com/s/fk3e75kwkee9g6q/linux-libc-dev_5.9.16-1_i386.deb?dl=1"

- name: Install 15khz kernel debs. 64 bit.
  apt:
    deb: "{{ item }}"
  with_items:
    - /root/linux-image-5.9.16_5.9.16-1_amd64.deb
    - /root/linux-headers-5.9.16_5.9.16-1_amd64.deb
    - /root/linux-libc-dev_5.9.16-1_amd64.deb
  when: ansible_architecture == 'x86_64'

- name: Install 15khz kernel debs. 32 bit.
  apt:
    deb: "{{ item }}"
  with_items:
    - /root/linux-image-5.9.16_5.9.16-1_i386.deb
    - /root/linux-headers-5.9.16_5.9.16-1_i386.deb
    - /root/linux-libc-dev_5.9.16-1_i386.deb
  when: ansible_architecture == 'i386'

- name: Remove deb files.
  file:
    path: "/root/{{ item }}"
    state: absent
  with_items:
    - linux-image-5.9.16_5.9.16-1_amd64.deb
    - linux-headers-5.9.16_5.9.16-1_amd64.deb
    - linux-libc-dev_5.9.16-1_amd64.deb
    - linux-image-5.9.16_5.9.16-1_i386.deb
    - linux-headers-5.9.16_5.9.16-1_i386.deb
    - linux-libc-dev_5.9.16-1_i386.deb

- name: Remove old kernel links. Debian.
  file:
    path: "/{{ item }}"
    state: absent
  with_items:
    - initrd.img
    - vmlinuz
  when: ansible_distribution == 'Debian'

- name: Create new kernel links. Debian.
  file:
    src: "boot/{{ item }}-5.9.16"
    dest: "/{{ item }}"
    state: link
  with_items:
    - initrd.img
    - vmlinuz
  when: ansible_distribution == 'Debian'

- name: Remove old kernel links. Ubuntu.
  file:
    path: "/boot/{{ item }}"
    state: absent
  with_items:
    - initrd.img
    - vmlinuz
  when: ansible_distribution == 'Ubuntu'

- name: Create new kernel links. Ubuntu.
  file:
    src: "{{ item }}-5.9.16"
    dest: "/boot/{{ item }}"
    state: link
  with_items:
    - initrd.img
    - vmlinuz
  when: ansible_distribution == 'Ubuntu'

- name: Check if there is grub configuration.
  stat:
    path: "/etc/default/grub"
  register: grub

- name: Change grub cmdline defaults for ATI
  replace:
    dest: "/etc/default/grub"
    regexp: '^(.*)GRUB_CMDLINE_LINUX_DEFAULT=(.*)$'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="vga=0x311 video=VGA-1:640x480iec"'
  register: grubati
  when:
    - grub.stat.exists == true
    - card == "ati"

- name: Change grub cmdline defaults for INTEL
  replace:
    dest: "/etc/default/grub"
    regexp: '^(.*)GRUB_CMDLINE_LINUX_DEFAULT=(.*)$'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="vga=0x311 video=VGA-1:1280x480iec"'
  register: grubintel
  when:
    - grub.stat.exists == true
    - card == "intel"

- name: Update grub config.
  command: /usr/sbin/update-grub
  when: (grubati.changed == true) or (grubintel.changed == true)
