
---
- name: Install original MAME to get the dependencies.
  apt:
    name: mame

- name: Install xorg-dev.
  apt:
    name: xorg-dev

- name: Check if exists a groovymame installation.
  stat:
    path: "/usr/local/bin/groovymame"
  register: groovy

- name: Check if exists a groovymame_226 installation.
  stat:
    path: "/usr/local/bin/groovymame_226"
  register: groovy_226

- name: Download and extract old groovymame. 64 bit.
  unarchive:
    src: https://github.com/antonioginer/GroovyMAME/releases/download/gm0226sr017s/groovymame64_0226.017s_linux.tar.bz2
    dest: /usr/local/bin
    remote_src: yes
  when:
    - groovy_226.stat.exists == false
    - ansible_architecture == 'x86_64'

- name: Download and extract old groovymame. 32 bit.
  unarchive:
    src: "https://www.dropbox.com/s/bpzayv77kaj5wjs/groovymame32_0226_linux.tar.bz2?dl=1"
    dest: /usr/local/bin
    remote_src: yes
  when:
    - groovy_226.stat.exists == false
    - ansible_architecture == 'i386'

- name: Move old groovymame to groovymame_226
  command: mv /usr/local/bin/groovymame /usr/local/bin/groovymame_226

- name: Download and extract groovymame. 64 bit.
  unarchive:
    src: https://github.com/antonioginer/GroovyMAME/releases/download/gm0227sr017t/groovymame64_0227.017t_linux.tar.bz2
    dest: /usr/local/bin
    remote_src: yes
  when:
    - groovy.stat.exists == false
    - ansible_architecture == 'x86_64'

- name: Download and extract groovymame. 32 bit.
  unarchive:
    src: "https://www.dropbox.com/s/o9masouk2oa8awz/groovymame32_0227_linux.tar.bz2?dl=1"
    dest: /usr/local/bin
    remote_src: yes
  when:
    - groovy.stat.exists == false
    - ansible_architecture == 'i386'

- name: Create config dirs.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/skel/mame/roms"

- name: Copy configurations.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "etc/skel/mame/roms/wrally.zip"
    - "etc/skel/mame.ini"

- name: Change mame.ini defaults for INTEL
  replace:
    dest: "/etc/skel/mame.ini"
    regexp: 'dotclock_min              0'
    replace: 'dotclock_min              25.0'
  when: card == "intel"

- name: Change mame.ini defaults for INTEL
  replace:
    dest: "/etc/skel/mame.ini"
    regexp: 'aspect                    auto'
    replace: 'aspect                     1:1'
  when: card == "intel"
