---
- name: Install retroarch to get all the dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - retroarch
    - libqt5concurrent5

- name: Copy configurations.
  copy:
    src: "{{ role_path }}/files/etc/retroarch{{ card }}.cfg"
    dest: "/etc/retroarch.cfg"
    mode: 0644

- name: Copy retroarch intel script.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/retroarch_intel"
    dest: "/usr/local/bin/retroarch_intel"
    mode: 0755

- name: Copy retroarch ati script.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/retroarch_ati"
    dest: "/usr/local/bin/retroarch_ati"
    mode: 0755

- name: Copy retroarch desktop file for intel.
  copy:
    src: "/usr/share/applications/retroarch.desktop"
    dest: "/usr/share/applications/retroarch_intel.desktop"
    mode: 0644
    remote_src: yes

- name: Modify retroarch desktop file.
  lineinfile:
    dest: /usr/share/applications/retroarch.desktop
    regexp: 'Exec=retroarch'
    line: 'Exec=/usr/local/bin/retroarch_ati'
    backrefs: yes

- name: Modify retroarch_intel desktop file.
  lineinfile:
    dest: /usr/share/applications/retroarch_intel.desktop
    regexp: 'Exec=retroarch'
    line: 'Exec=/usr/local/bin/retroarch_intel'
    backrefs: yes
