#set spanish timezone
---
  - name: set spanish timezone.
    file:
      src: /usr/share/zoneinfo/Europe/Madrid
      dest: /etc/localtime
      state: link
    register: localtime

  - name: Dpkg-reconfigure tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    when: localtime.changed  == true
